name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10 # Specify your desired Python version here
  - pip
  - pip:
    - streamlit>=1.0.0
    - tensorflow>=2.10.0 # Use a specific, known-compatible TensorFlow version
    - pandas>=1.0.0
    - numpy>=1.20.0
    - opencv-python-headless>=4.5.0
    - Pillow>=8.0.0
    - h5py>=3.0.0
